// ==========================================
// 🎯 4. 주간 도전 과제 (26종 챌린지 전체 데이터베이스)
// ==========================================

const WEEKLY_CHALLENGES = [
    {
        id: 1,
        title: "1. Lights out! (암흑천지!)",
        nameKr: "암흑천지! (Lights out!)",
        nameEn: "Lights out!",
        map: "6 Tanglewood Drive (탱글우드)",
        quote: "Get your candles at the ready, all the lights are out! (양초를 준비하세요, 모든 불이 꺼졌습니다!)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "기본 100%",
        speed: "플레이어 100% / 유령 100%",
        hiding: "보통",
        breaker: "<strong>파손됨 (Broken / 영구 정전)</strong> (지도 미표시)",
        weather: "무작위",
        doors: "시작 시 열린 문 많음 (High)",
        cursed: "뮤직박스 (Music Box)",
        missingItems: "🚫 <strong>손전등 전종 (Flashlights)</strong>, 모션 센서, 지향성 마이크, 사운드 레코더, 사운드 센서, 삼각대, 포토 카메라 1개 누락",
        availableItems: "📦 양초 4개, 점화 도구 4개, 7종 증거 수집 장비, 십자가, 정화향초, 소금, 안정제",
        strategy: "두꺼비집이 파손되어 전등을 켤 수 없으며 손전등도 지급되지 않습니다. 트럭에서 <strong>양초와 라이터를 먼저 챙겨 주요 동선에 촛불을 켜두어 시야와 정신력을 방어</strong>하세요. 시작 시 열린 문이 많으므로 온도계와 소리를 이용해 고스트 룸을 특정해야 합니다."
    },
    {
        id: 2,
        title: "2. Speed Demons (스피드 데몬)",
        nameKr: "스피드 데몬 (Speed Demons)",
        nameEn: "Speed Demons",
        map: "Maple Lodge Campsite (메이플 롯지)",
        quote: "There must be something in the air, everyone's going crazy! (공기 중에 뭔가가 있어요, 모두가 미쳐 날뛰고 있습니다!)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "기본 100%",
        speed: "<strong>플레이어 150% / 유령 150% (초고속)</strong>",
        hiding: "보통",
        breaker: "꺼짐",
        weather: "무작위",
        doors: "시작 시 열린 문 많음 (High) / 방 변경 빈도: 매우 높음 (Very High) / 활동성 & 이벤트: 높음 (High)",
        cursed: "원숭이 손 (Monkey Paw)",
        missingItems: "🚫 <strong>점화 도구 (Igniters - 라이터/성냥 전면 차단)</strong>, 모션 센서",
        availableItems: "📦 손전등, 7종 증거 수집 장비, 십자가, 정화향초(불 붙이기 불가), 소금, 안정제, 카메라",
        strategy: "유령과 플레이어 모두 1.5배로 매우 빠르며 유령이 방을 극단적으로 자주 바꿉니다. <strong>라이터가 없어 정화향초를 태울 수 없으므로</strong> 사냥이 시작되면 향초에 의존하지 말고 넓은 캠프장 동선을 활용해 시야를 끊고 은신처로 대피해야 합니다."
    },
    {
        id: 3,
        title: "3. Detectives only (명탐정 전용)",
        nameKr: "명탐정 전용 (Detectives only)",
        nameEn: "Detectives only",
        map: "42 Edgefield Road (엣지필드)",
        quote: "Put your detective skills to the test, this ghost is giving nothing away! (탐정 능력을 시험해보세요, 이 유령은 단서를 전혀 주지 않습니다!)",
        evidences: "<strong>0개 (무증거 모드)</strong>",
        setupTime: "0초",
        sanity: "기본 100%",
        speed: "플레이어 100% / 유령 100%",
        hiding: "보통",
        breaker: "꺼짐",
        weather: "무작위",
        doors: "기본 / 배회, 방 변경, 활동성, 사냥 시간: 보통 (Medium)",
        cursed: "위자보드 (Ouija Board)",
        missingItems: "🚫 없음 (모든 장비 정상 지급)",
        availableItems: "📦 손전등, 십자가, 정화향초, 점화 도구, 소금, 안정제, 7종 조사 도구 풀세트",
        strategy: "증거가 나오지 않는 0증거 모드입니다. 위자보드로 고스트 룸을 즉시 확인한 뒤, <strong>소금 피적 여부(레이스), 사냥 중 발소리 템포 및 속도(모로이/타예/데오겐), 향초 방어 시간(스피릿/데몬)</strong> 등의 고유 특성으로 유령을 특정해야 합니다."
    },
    {
        id: 4,
        title: "4. Hide and Seek: Seeker (숨바꼭질: 술래)",
        nameKr: "숨바꼭질: 술래 (Hide and Seek: Seeker)",
        nameEn: "Hide and Seek: Seeker",
        map: "Brownstone High School (브라운스톤 고등학교)",
        quote: "There's a very quiet ghost hiding somewhere, can you find it? (어딘가에 매우 조용한 유령이 숨어 있습니다, 찾을 수 있나요?)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "<strong>정신력 감소율 0% (영구 100% 유지)</strong> / 안정제 회복량 35%",
        speed: "플레이어 100% / 유령 100%",
        hiding: "<strong>없음 (None)</strong>",
        breaker: "꺼짐",
        weather: "무작위",
        doors: "시작 시 열린 문 없음 / 방 변경 없음 / <strong>친절한 유령: 켜짐 (On - 공격/사냥 절대 안 함)</strong>",
        cursed: "없음 (None)",
        missingItems: "🚫 <strong>정화향초 (Incense)</strong>, <strong>십자가 (Crucifixes)</strong>",
        availableItems: "📦 손전등, 7종 증거 수집 장비, 지향성 마이크, 사운드 센서, 소금, 안정제, 카메라, 삼각대",
        strategy: "<strong>유령이 절대 사냥을 하지 않으므로 사망 위험이 0%</strong>입니다. 넓은 고등학교에서 활동성이 극도로 낮은 유령을 찾아내는 것이 목표이므로, 지향성 마이크와 온도계를 들고 복도를 빠르게 돌며 10°C 이하 교실을 찾으세요."
    },
    {
        id: 5,
        title: "5. Hide and Seek: Hide! (숨바꼭질: 숨어라!)",
        nameKr: "숨바꼭질: 숨어라! (Hide and Seek: Hide!)",
        nameEn: "Hide and Seek: Hide!",
        map: "Point Hope (포인트 호프 등대)",
        quote: "This ghost wants to play a game, you better hide quick! (이 유령은 게임을 하고 싶어 합니다, 어서 빨리 숨는 게 좋을 거예요!)",
        evidences: "3개",
        setupTime: "<strong>1분 (준비 시간 60초)</strong>",
        sanity: "<strong>시작 0%</strong> / 안정제 회복량 0% / 정신력 감소율 150%",
        speed: "플레이어 100% / 유령 100%",
        hiding: "<strong>매우 많음 (Very High - 은신처 대다수 개방)</strong>",
        breaker: "꺼짐",
        weather: "무작위",
        doors: "시작 시 열린 문 적음 / 헌팅 유예 시간 5초 / 킬 시 사냥 연장 높음",
        cursed: "없음 (None)",
        missingItems: "🚫 <strong>헤드 기어 (Head Gear)</strong>, <strong>지향성 마이크 (Parabolic Microphones)</strong>",
        availableItems: "📦 손전등, 십자가, 정화향초, 점화 도구, 7종 증거 수집 장비, 소금, 카메라",
        strategy: "정신력이 0%이고 약으로 회복할 수 없어 1분의 준비 시간이 끝나면 연속 사냥이 시작됩니다. <strong>초반 1분 안에 등대 계단을 뛰어올라가 십자가를 깔고 방을 찾아야 하며</strong>, 사냥 유예 시간이 5초로 길므로 침착하게 가까운 은신처로 숨으세요."
    },
    {
        id: 6,
        title: "6. Frostbitten (동상)",
        nameKr: "동상 (Frostbitten)",
        nameEn: "Frostbitten",
        map: "Camp Woodwind (우드윈드 캠프장)",
        quote: "It's so cold that it's slowing everyone down, including the ghost! (너무 추워서 유령을 포함한 모두가 느려지고 있습니다!)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "기본 / 안정제 회복량 100%",
        speed: "<strong>플레이어 75% / 유령 75% (저속 이동)</strong>",
        hiding: "보통",
        breaker: "<strong>파손됨 (Broken)</strong>",
        weather: "<strong>눈 (Snow / 폭설)</strong>",
        doors: "시작 시 열린 문 많음 (High) / 활동성 & 사냥 시간: 보통",
        cursed: "없음 (None)",
        missingItems: "🚫 <strong>점화 도구 (Igniters)</strong>, <strong>양초 (Firelights)</strong>, <strong>정화향초 (Incense)</strong>",
        availableItems: "📦 손전등, 7종 증거 수집 장비, 십자가, 소금, 안정제, 카메라, 삼각대",
        strategy: "눈 날씨와 고장 난 차단기 때문에 기본 기온이 매우 낮습니다. 입김이 나온다고 무조건 서늘함 증거로 체크하지 말고 온도계로 영하(0°C 미만)를 확인해야 합니다. 향초가 없지만 유령 속도가 75%로 느리므로 침착하게 도주하세요."
    },
    {
        id: 7,
        title: "7. Do as I Command (명령대로 하라)",
        nameKr: "명령대로 하라 (Do as I Command)",
        nameEn: "Do as I Command",
        map: "Sunny Meadows (써니 메도우 본관)",
        quote: "You'll have to force this ghost to give you evidence, luckily, we've found some extra items to help you out. (유령이 증거를 내놓도록 강제해야 합니다. 다행히 도움이 될 만한 아이템들을 찾아두었습니다.)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "기본 100% / 안정제 회복량 50%",
        speed: "플레이어 100% / 유령 100%",
        hiding: "보통",
        breaker: "꺼짐",
        weather: "무작위",
        doors: "시작 시 열린 문 많음 / 헌팅 유예 시간 2초 / 사냥 지속 시간: 짧음 (Low)",
        cursed: "<strong>7종 저주받은 물건 전부 스폰 (All)</strong>",
        missingItems: "🚫 없음 (모든 장비 정상 지급)",
        availableItems: "📦 손전등, 십자가, 정화향초, 점화 도구, 7종 증거 수집 장비 풀세트",
        strategy: "<strong>예배당에 7개의 저주받은 물건이 모두 스폰</strong>됩니다. 위자보드로 방 위치를 묻거나 거울/뮤직박스를 활용해 유령의 방을 즉시 특정하고, 사냥 시간이 짧으므로 정화향초를 챙겨 안전하게 증거를 수집하세요."
    },
    {
        id: 8,
        title: "8. Tortoise and the Hare: Hare (토끼와 거북이: 토끼)",
        nameKr: "토끼와 거북이: 토끼 (Tortoise and the Hare: Hare)",
        nameEn: "Tortoise and the Hare: Hare",
        map: "Bleasdale Farmhouse (블리즈데일)",
        quote: "Give it your all, this ghost is feeling especially frail. (최선을 다하세요, 이번 유령은 유난히 허약한 상태입니다.)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "기본 100%",
        speed: "<strong>플레이어 125% (빠름) / 유령 50% (극도로 느림)</strong>",
        hiding: "보통",
        breaker: "꺼짐",
        weather: "무작위",
        doors: "시작 시 열린 문 많음 (High)",
        cursed: "무작위",
        missingItems: "🚫 없음 (모든 장비 정상 지급)",
        availableItems: "📦 모든 조사 및 방어 장비 풀세트",
        strategy: "플레이어는 빠르고 유령은 기어가듯 움직입니다(50%). 사냥이 시작되어도 걸어서 따돌릴 수 있을 만큼 난이도가 매우 낮으므로 편안하게 3가지 증거를 수집하고 탈출하세요."
    },
    {
        id: 9,
        title: "9. Tortoise and the Hare: Tortoise (토끼와 거북이: 거북이)",
        nameKr: "토끼와 거북이: 거북이 (Tortoise and the Hare: Tortoise)",
        nameEn: "Tortoise and the Hare: Tortoise",
        map: "Grafton Farmhouse (그라프톤 농가)",
        quote: "After last week you're feeling a bit worn out, and to make matters worse, the ghost has recovered! (지난주 탓에 피로가 쌓였는데, 설상가상으로 유령이 기운을 회복했습니다!)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "기본 100%",
        speed: "<strong>플레이어 75% (느림) / 유령 150% (초고속)</strong>",
        hiding: "보통",
        breaker: "꺼짐",
        weather: "무작위",
        doors: "시작 시 열린 문 많음 / 방 변경 높음 / 활동성 높음 / 사냥 시간 짧음 / 킬 시 연장 높음",
        cursed: "무작위",
        missingItems: "🚫 <strong>양초 2개 누락 (2 Firelights Missing)</strong>",
        availableItems: "📦 손전등, 십자가, 정화향초, 점화 도구, 7종 증거 수집 장비",
        strategy: "플레이어는 느리고 유령은 1.5배로 매우 빠릅니다. 사냥 중 유령에게 들키면 도주가 거의 불가능하므로, <strong>방 입구에 십자가를 촘촘히 깔고 정화향초와 라이터를 상시 손에 쥔 채 조사</strong>해야 합니다."
    },
    {
        id: 10,
        title: "10. Gotta Go Fast! (스피드런!)",
        nameKr: "스피드런! (Gotta Go Fast!)",
        nameEn: "Gotta Go Fast!",
        map: "Prison (교도소)",
        quote: "No hiding, no sanity, get going! (은신처도 없고, 정신력도 없습니다. 어서 달리세요!)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "<strong>시작 0%</strong> / 안정제 회복량 0% / <strong>정신력 모니터 꺼짐</strong>",
        speed: "<strong>플레이어 125% / 유령 125%</strong>",
        hiding: "<strong>없음 (None - 모든 은신처 100% 차단)</strong>",
        breaker: "<strong>파손됨 (Broken)</strong>",
        weather: "무작위",
        doors: "시작 시 열린 문 많음 (High)",
        cursed: "무작위",
        missingItems: "🚫 <strong>사운드 레코더 1개</strong>, <strong>정화향초 (Incense)</strong>, <strong>십자가 (Crucifixes)</strong>",
        availableItems: "📦 손전등, 7종 증거 수집 장비, 소금, 카메라, 삼각대",
        strategy: "정신력 0%, 은신처 없음, 방어 장비(향초/십자가) 전무라는 극한의 조건입니다. 유령에게 들키지 않도록 교도소 A/B동 문 뒤나 가구 뒤로 시야를 숨겨야 하며, 도트와 카메라 등을 트럭에서 확인하는 원격 플레이가 필수적입니다."
    },
    {
        id: 11,
        title: "11. Sanity Survival (정신력 생존)",
        nameKr: "정신력 생존 (Sanity Survival)",
        nameEn: "Sanity Survival",
        map: "10 Ridgeview Court (리지뷰)",
        quote: "Sanity is a scarce resource with no pills or lights. Be careful finding this Nightmare ghost. (약도 불빛도 없어 정신력이 부족합니다. 악몽 유령을 조심해서 찾아내세요.)",
        evidences: "<strong>2개 (악몽 룰 적용)</strong>",
        setupTime: "0초",
        sanity: "시작 75% / 안정제 회복량 0% / <strong>정신력 모니터 꺼짐</strong>",
        speed: "플레이어 100% / 유령 100%",
        hiding: "보통",
        breaker: "<strong>파손됨 (Broken)</strong>",
        weather: "무작위",
        doors: "시작 시 열린 문 많음 / 헌팅 유예 시간 2초",
        cursed: "<strong>타로 카드 (Tarot Cards) & 부두 인형 (Voodoo Doll) 2종 스폰</strong>",
        missingItems: "🚫 <strong>정신력 안정제 3개</strong>, <strong>정화향초 (Incense)</strong>, <strong>십자가 1개 누락</strong>",
        availableItems: "📦 손전등, 십자가 1개, 점화 도구, 양초, 7종 증거 수집 장비",
        strategy: "증거가 2개만 주어지며 두꺼비집 파손 및 안정제 부족으로 정신력이 빠르게 소진됩니다. 2개의 증거를 빠르게 획득한 뒤 유령의 특수 행동을 파악해야 하며, 타로 카드로 정신력을 회복하거나 강제 사냥을 유도할 수 있습니다."
    },
    {
        id: 12,
        title: "12. Speedrun! (스피드런!)",
        nameKr: "스피드런! (Speedrun!)",
        nameEn: "Speedrun!",
        map: "6 Tanglewood Drive (탱글우드)",
        quote: "Maybe you could start a timer, how quickly can you find this ghost's identity? (타이머를 맞춰보세요, 얼마나 빨리 유령의 정체를 밝혀낼 수 있을까요?)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "기본 100%",
        speed: "<strong>플레이어 150% (초고속)</strong> / 유령 100%",
        hiding: "적음 (Low)",
        breaker: "<strong>켜진 상태로 시작 (On)</strong>",
        weather: "무작위",
        doors: "시작 시 열린 문 없음 / 배회 낮음 / 활동성 & 이벤트: 높음 (High)",
        cursed: "<strong>7종 저주받은 물건 전부 스폰 (All)</strong>",
        missingItems: "🚫 <strong>사운드 레코더 (Sound Recorders)</strong>",
        availableItems: "📦 손전등, 십자가, 정화향초, 점화 도구, 7종 증거 수집 장비 풀세트",
        strategy: "두꺼비집이 켜져 있고 플레이어 속도가 150%이며 집안에 모든 저주받은 물건이 스폰됩니다. 거울이나 위자보드로 5초 만에 방을 찾고 3개 증거를 즉시 채워 1~2분 만에 클리어할 수 있는 파밍용 챌린지입니다."
    },
    {
        id: 13,
        title: "13. Survival of the Fittest (적자생존)",
        nameKr: "적자생존 (Survival of the Fittest)",
        nameEn: "Survival of the Fittest",
        map: "42 Edgefield Road (엣지필드)",
        quote: "You've got no pills, no sanity and no evidence to work with. It's gonna be a tough one! (약도 없고, 정신력도 없고, 증거도 없습니다. 힘든 조사가 될 거예요!)",
        evidences: "<strong>0개 (무증거 모드)</strong>",
        setupTime: "0초",
        sanity: "<strong>시작 0%</strong> / 안정제 회복량 0%",
        speed: "플레이어 100% / 유령 100%",
        hiding: "<strong>매우 많음 (Very High - 은신처 대부분 개방)</strong>",
        breaker: "켜짐 (On)",
        weather: "무작위",
        doors: "시작 시 열린 문 많음 / 헌팅 유예 시간 5초 / 킬 시 사냥 연장 높음",
        cursed: "원숭이 손 (Monkey Paw)",
        missingItems: "🚫 <strong>안정제 2개</strong>, <strong>온도계</strong>, <strong>UV 라이트</strong>, <strong>라이팅북</strong>, <strong>DOTS 프로젝터</strong>, <strong>비디오 카메라</strong>, <strong>삼각대</strong>",
        availableItems: "📦 손전등, EMF 측정기, 스피릿 박스, 십자가, 정화향초, 소금, 포토 카메라",
        strategy: "증거 수집 장비 대다수가 차단된 상태에서 0증거로 추리해야 합니다. 다행히 사냥 유예 시간이 5초이고 은신처가 많으므로, <strong>사냥 시 발소리 속도, 깜빡임 주기, 소금 반응, 향초 저지 시간</strong>으로 유령을 좁혀내야 합니다."
    },
    {
        id: 14,
        title: "14. Primitive (원시적 조사)",
        nameKr: "원시적 조사 (Primitive)",
        nameEn: "Primitive",
        map: "10 Ridgeview Court (리지뷰)",
        quote: "I'm afraid all of the electronic equipment has short-circuited, you'll have to make do without. (모든 전자 장비가 합선된 것 같습니다. 전자 장비 없이 해결해야 합니다.)",
        evidences: "3개",
        setupTime: "<strong>5분 (준비 시간 300초 제공)</strong>",
        sanity: "기본 100% / 안정제 회복량 40%",
        speed: "플레이어 100% / 유령 100%",
        hiding: "<strong>매우 많음 (Very High)</strong>",
        breaker: "<strong>파손됨 (Broken)</strong>",
        weather: "무작위",
        doors: "시작 시 열린 문 없음 / 헌팅 유예 시간 5초 / 사냥 지속 시간 짧음",
        cursed: "위자보드 (Ouija Board)",
        missingItems: "🚫 <strong>모든 전자 장비 전면 차단:</strong> 헤드기어, 안정제, 모션/사운드 센서, 마이크, 레코더, EMF, 카메라, 스피릿박스, DOTS, 손전등, 비디오카메라, 삼각대",
        availableItems: "📦 <strong>아날로그 장비만 지급:</strong> 양초, 점화 도구, 십자가, 정화향초, 소금, 고스트 라이팅 북, 자외선 형광봉(1티어), 수은 온도계(1티어)",
        strategy: "전자 장비가 100% 차단되므로 <strong>양초 불빛으로 시야를 밝히고, 수은 온도계, 형광봉, 라이팅 북으로 증거를 확인</strong>해야 합니다. 전자기기가 없어 헌팅 중 라이주 버프나 전자기 교란 위험이 없습니다."
    },
    {
        id: 15,
        title: "15. Vulnerable (무방비 상태)",
        nameKr: "무방비 상태 (Vulnerable)",
        nameEn: "Vulnerable",
        map: "13 Willow Street (윌로우)",
        quote: "You'll be going into this one with no defenses, be careful out there. (아무런 방어 수단 없이 들어가야 합니다. 조심하세요.)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "기본 100%",
        speed: "플레이어 100% / 유령 100%",
        hiding: "<strong>없음 (None - 모든 은신처 차단)</strong>",
        breaker: "꺼짐",
        weather: "무작위",
        doors: "시작 시 열린 문 많음 (High)",
        cursed: "부두 인형 (Voodoo Doll)",
        missingItems: "🚫 <strong>정화향초 (Incense)</strong>, <strong>십자가 (Crucifixes)</strong>, 정신력 안정제, 양초 2개, 사운드 레코더",
        availableItems: "📦 손전등, 7종 증거 수집 장비, 소금, 카메라, 삼각대",
        strategy: "십자가와 향초가 없어 사냥을 막거나 유령을 실명시킬 수 없고 은신처도 없습니다. 윌로우 스트리트의 거실 가구 및 주방 카운터를 빙빙 도는 <strong>루핑(Looping) 동선을 미리 숙지</strong>하고 전등을 켜 정신력을 관리해야 합니다."
    },
    {
        id: 16,
        title: "16. Missed delivery (배송 누락)",
        nameKr: "배송 누락 (Missed delivery)",
        nameEn: "Missed delivery",
        map: "Brownstone High School (브라운스톤 고등학교)",
        quote: "We didn't receive our full equipment delivery this week, so you won't have everything you might need! (이번 주 장비 배송이 제대로 오지 않아 필요한 장비가 부족할 것입니다!)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "기본 100%",
        speed: "플레이어 100% / 유령 100%",
        hiding: "보통",
        breaker: "꺼짐",
        weather: "무작위",
        doors: "시작 시 열린 문 많음 (High)",
        cursed: "무작위",
        missingItems: "🚫 <strong>모든 아이템이 딱 '1개씩'만 제공됨 (Missing: all but 1 of every item)</strong>",
        availableItems: "📦 모든 종류의 장비가 트럭에 정확히 1개씩만 구비됨",
        strategy: "모든 장비가 단 1개씩만 제공되므로 장비를 잃어버리거나 낭비해선 안 됩니다. 손전등도 1개뿐이므로 멀티플레이 시 팀원들은 비디오 카메라나 양초를 나눠 들고 수색해야 합니다."
    },
    {
        id: 17,
        title: "17. Audio only (오디오 전용)",
        nameKr: "오디오 전용 (Audio only)",
        nameEn: "Audio only",
        map: "Bleasdale Farmhouse (블리즈데일)",
        quote: "We've managed to get hold of some extra audio equipment. You'll have to use your ears on this one. (추가 음향 장비를 확보했습니다. 귀를 기울여야 할 것입니다.)",
        evidences: "3개",
        setupTime: "<strong>5분 (준비 시간 300초)</strong>",
        sanity: "기본 100% / 안정제 회복량 40% / 감소율 150%",
        speed: "플레이어 100% / 유령 100%",
        hiding: "<strong>매우 많음 (Very High)</strong>",
        breaker: "켜짐 (On)",
        weather: "무작위",
        doors: "시작 시 열린 문 없음 / 사냥 시간 짧음",
        cursed: "뮤직박스 (Music Box)",
        missingItems: "🚫 <strong>온도계 (Thermometers)</strong>, <strong>자외선 라이트 (UV Lights)</strong>, <strong>비디오 카메라 (Video Cameras)</strong>, 삼각대, 안정제, 양초 2개",
        availableItems: "📦 손전등, EMF 측정기, 스피릿 박스, 고스트 라이팅 북, DOTS, 지향성 마이크, 사운드 센서/레코더, 십자가, 향초",
        strategy: "온도계와 비디오 카메라가 없어 방 찾기가 까다롭습니다. <strong>지향성 마이크와 사운드 센서를 설치해 소리가 나는 방을 찾고</strong>, EMF/스피릿박스/DOTS/라이팅북으로 증거를 확인하세요."
    },
    {
        id: 18,
        title: "18. Technophilia (기술 애호가)",
        nameKr: "기술 애호가 (Technophilia)",
        nameEn: "Technophilia",
        map: "Bleasdale Farmhouse (블리즈데일)",
        quote: "We've thrown out all of those prehistoric items, this contract is all about technology! (원시적인 물건들은 다 버렸습니다. 이번 조사는 오직 첨단 기술뿐입니다!)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "기본 100%",
        speed: "플레이어 100% / 유령 100%",
        hiding: "보통",
        breaker: "꺼짐",
        weather: "무작위",
        doors: "시작 시 열린 문 많음 (High)",
        cursed: "타로 카드 (Tarot Cards)",
        missingItems: "🚫 <strong>아날로그/방어 장비 전면 차단:</strong> 점화 도구, 양초, 정화향초, 소금, 십자가, 고스트 라이팅 북",
        availableItems: "📦 <strong>모든 최첨단 전자 장비 풀세트:</strong> 헤드기어, 손전등, 비디오카메라, EMF, DOTS, UV 라이트, 스피릿박스, 온도계, 사운드/모션 센서",
        strategy: "십자가와 향초가 없어 사냥 방어가 불가능하지만, 3티어 전자 계측기들이 풀세트로 지원됩니다. 첨단 센서와 카메라로 고스트 룸을 즉시 찾아내고 사냥 전에 빠르게 3개 증거를 모아 탈출하세요."
    },
    {
        id: 19,
        title: "19. No Evidence (무증거)",
        nameKr: "무증거 (No Evidence)",
        nameEn: "No Evidence",
        map: "Grafton Farmhouse (그라프톤 농가)",
        quote: "These ghosts really don't wanna help you out, but we're sure you're up to the task. (유령들이 전혀 협조할 생각이 없지만, 여러분이라면 해낼 수 있을 겁니다.)",
        evidences: "<strong>0개 (무증거 모드)</strong>",
        setupTime: "0초",
        sanity: "기본 100% / 안정제 회복량 25%",
        speed: "플레이어 100% / 유령 100%",
        hiding: "적음 (Low)",
        breaker: "꺼짐 (지도 미표시)",
        weather: "무작위",
        doors: "시작 시 열린 문 많음 / 이벤트 빈도 높음 / 유예 시간 2초",
        cursed: "유령의 거울 (Haunted Mirror)",
        missingItems: "🚫 없음 (모든 장비 정상 지급)",
        availableItems: "📦 모든 조사 및 방어 장비 풀세트",
        strategy: "증거가 0개이므로 <strong>유령의 거울로 방을 확인</strong>한 뒤, 소금, 향초 저지 쿨타임, 유령의 이동 속도와 특수 상호작용(오니의 투명화 없음, 팬텀 사진 촬영 시 실종 등)을 시험해 유령을 추론해야 합니다."
    },
    {
        id: 20,
        title: "20. The Apocalypse Draws Near (다가오는 아포칼립스)",
        nameKr: "다가오는 아포칼립스 (The Apocalypse Draws Near)",
        nameEn: "The Apocalypse Draws Near",
        map: "Sunny Meadows Restricted (써니 메도우 구역제한)",
        quote: "The hardest possible challenge, but with normal investigator speed. Good luck. (가장 어려운 도전이지만 조사관의 속도는 정상입니다. 행운을 빕니다.)",
        evidences: "<strong>0개 (무증거 극한 난이도)</strong>",
        setupTime: "0초",
        sanity: "<strong>시작 0%</strong> / 안정제 회복량 0% / <strong>정신력&활동성 모니터 꺼짐</strong>",
        speed: "플레이어 100% / <strong>유령 150% (초고속)</strong>",
        hiding: "<strong>없음 (None)</strong>",
        breaker: "<strong>파손됨 (Broken)</strong>",
        weather: "<strong>폭우 (Heavy Rain)</strong>",
        doors: "시작 시 열린 문 많음 / <strong>손전등 꺼짐 (Off)</strong> / <strong>헌팅 유예 시간 0초 (즉시 킬)</strong>",
        cursed: "없음 (None)",
        missingItems: "🚫 손전등 전면 사용 불가",
        availableItems: "📦 십자가, 정화향초, 점화 도구, 소금, 7종 조사 장비",
        strategy: "<strong>아포칼립스 골드 트로피급 극한 설정</strong>입니다. 진입 즉시 0초 유예로 150% 속도의 사냥이 터집니다. 문 뒤에 정화향초와 라이터를 든 채 대기하며, 유령의 발소리 속도와 헌팅 깜빡임만을 확인하고 유령을 찍어 맞히고 탈출해야 합니다."
    },
    {
        id: 21,
        title: "21. Slow and Steady (느림의 미학)",
        nameKr: "느림의 미학 (Slow and Steady)",
        nameEn: "Slow and Steady",
        map: "Camp Woodwind (우드윈드 캠프장)",
        quote: "This ghost may be slow, but its angry. Keep on your toes! (유령은 느리지만 매우 화가 나 있습니다. 긴장하세요!)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "<strong>시작 0%</strong> / 안정제 회복량 0%",
        speed: "플레이어 100% / <strong>유령 50% (매우 느림)</strong>",
        hiding: "<strong>없음 (None)</strong>",
        breaker: "꺼짐",
        weather: "<strong>폭우 (Heavy Rain)</strong>",
        doors: "시작 시 열린 문 많음 / 헌팅 유예 시간 1초",
        cursed: "없음 (None)",
        missingItems: "🚫 없음 (모든 장비 정상 지급)",
        availableItems: "📦 모든 조사 및 방어 장비 풀세트",
        strategy: "정신력이 0%라 사냥이 즉시 시작되지만 유령 속도가 50%로 기어 다닙니다. 은신처는 없으나 플레이어가 걸어만 다녀도 유령을 완벽히 따돌릴 수 있으므로, 우드윈드 캠프장 테이블을 돌며 여유롭게 3가지 증거를 수집하세요."
    },
    {
        id: 22,
        title: "22. Paranormal Paparazzi (심령 파파라치)",
        nameKr: "심령 파파라치 (Paranormal Paparazzi)",
        nameEn: "Paranormal Paparazzi",
        map: "Point Hope (포인트 호프 등대)",
        quote: "You've got cameras, lights and sound. Find that ghost type! (카메라, 조명, 음향이 모두 준비되었습니다. 유령 유형을 밝혀내세요!)",
        evidences: "3개",
        setupTime: "<strong>2분 (준비 시간 120초)</strong>",
        sanity: "기본 100% / 안정제 회복량 35% / 감소율 150%",
        speed: "플레이어 100% / 유령 100%",
        hiding: "많음 (High)",
        breaker: "꺼짐",
        weather: "무작위",
        doors: "시작 시 열린 문 적음 / 헌팅 유예 시간 4초",
        cursed: "원숭이 손 (Monkey Paw)",
        missingItems: "🚫 <strong>정화향초, 십자가, 소금, 안정제, EMF 측정기, 온도계</strong>",
        availableItems: "📦 손전등, 포토 카메라, 비디오 카메라, 삼각대, DOTS, UV 라이트, 스피릿 박스, 라이팅 북, 음향 센서",
        strategy: "온도계와 EMF, 방어 장비가 빠진 촬영 전문 세팅입니다. <strong>비디오 카메라 야간 투시로 오브/DOTS를 확인하고, UV와 라이팅북, 스피릿박스 위주로 증거를 수집</strong>하세요. 사냥 유예 시간이 4초로 기므로 불빛이 깜빡이면 바로 은신처로 숨으세요."
    },
    {
        id: 23,
        title: "23. Hide and seek: Extreme (숨바꼭질: 익스트림)",
        nameKr: "숨바꼭질: 익스트림 (Hide and seek: Extreme)",
        nameEn: "Hide and seek: Extreme",
        map: "Camp Woodwind (우드윈드 캠프장)",
        quote: "This ghost wants to play a game, you better hide. (유령이 게임을 하고 싶어 합니다, 숨는 게 좋을 거예요.)",
        evidences: "3개",
        setupTime: "<strong>1분 (준비 시간 60초)</strong>",
        sanity: "<strong>시작 0%</strong> / 안정제 회복량 0%",
        speed: "플레이어 100% / <strong>유령 150% (초고속)</strong>",
        hiding: "적음 (Low)",
        breaker: "켜짐 (On)",
        weather: "무작위",
        doors: "시작 시 열린 문 많음 / <strong>손전등 꺼짐 (Off)</strong> / 방 변경 높음 / 헌팅 유예 5초 / 킬 시 연장 높음",
        cursed: "원숭이 손 (Monkey Paw)",
        missingItems: "🚫 <strong>손전등 (Flashlights)</strong>, <strong>정화향초 (Incense)</strong>, <strong>UV 라이트 (UV Lights)</strong>, 정신력 안정제",
        availableItems: "📦 십자가, 점화 도구, 양초, EMF, DOTS, 스피릿박스, 라이팅북, 온도계, 비디오카메라",
        strategy: "손전등과 향초가 없고 유령이 150%로 매우 빠릅니다. 1분의 준비 시간 동안 양초를 들고 들어가 텐트 구역에 불을 밝히고 십자가를 배치해야 합니다. 사냥 시 향초가 없으므로 유령의 시야를 피해 텐트 뒤로 숨어야 합니다."
    },
    {
        id: 24,
        title: "24. Glow in the Dark (야광의 밤)",
        nameKr: "야광의 밤 (Glow in the Dark)",
        nameEn: "Glow in the Dark",
        map: "42 Edgefield Road (엣지필드)",
        quote: "Some of our equipment has stopped working, hopefully this'll be enough for you to see. (일부 장비가 작동을 멈췄습니다. 이것만으로도 시야가 확보되길 바랍니다.)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "기본 100%",
        speed: "플레이어 100% / 유령 100%",
        hiding: "보통",
        breaker: "<strong>파손됨 (Broken)</strong>",
        weather: "무작위",
        doors: "시작 시 열린 문 많음 (High)",
        cursed: "무작위",
        missingItems: "🚫 <strong>손전등 (Flashlights)</strong>, <strong>비디오 카메라 (Video Cameras)</strong>, <strong>양초 (Firelights)</strong>, 모션 센서, 사운드 레코더, 삼각대",
        availableItems: "📦 <strong>자외선 UV 형광봉/라이트</strong>, EMF, DOTS, 스피릿박스, 라이팅북, 온도계, 십자가, 향초, 소금, 안정제",
        strategy: "손전등과 양초, 비디오 카메라가 모두 없습니다. <strong>자외선 형광봉(UV)을 켜서 들고 다니거나 바닥에 던져 은은한 야광 불빛으로 실내를 밝히며</strong> 수색해야 합니다. 형광봉은 헌팅 시에도 안전합니다."
    },
    {
        id: 25,
        title: "25. Deja Vu (데자뷔)",
        nameKr: "데자뷔 (Deja Vu)",
        nameEn: "Deja Vu",
        map: "6 Tanglewood Drive (탱글우드)",
        quote: "This one feels pretty nostalgic, don't you think? (꽤 익숙한 느낌이 들지 않나요?)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "기본 100%",
        speed: "<strong>플레이어 질주 불가 (Sprinting: Off)</strong> / <strong>유령 75% (느림)</strong>",
        hiding: "<strong>없음 (None)</strong>",
        breaker: "꺼짐 (지도 미표시)",
        weather: "가벼운 비 (Light Rain)",
        doors: "시작 시 열린 문 없음 / 헌팅 유예 시간 4초",
        cursed: "위자보드 (Ouija Board)",
        missingItems: "🚫 <strong>DOTS 프로젝터</strong>, 점화 도구 2개, 소금 1개, 사운드 레코더",
        availableItems: "📦 손전등, EMF 측정기, UV 라이트, 스피릿 박스, 라이팅 북, 온도계, 비디오 카메라, 십자가, 향초, 안정제",
        strategy: "파스모포비아 초기 클래식 버전을 오마주한 챌린지입니다. 플레이어가 달릴 수 없지만 유령 속도도 75%로 느립니다. <strong>DOTS 프로젝터가 없으므로 도트가 증거인 유령은 도트가 안 나와도 자동으로 추론</strong>할 수 있습니다."
    },
    {
        id: 26,
        title: "26. Tag! You're it! (술래잡기!)",
        nameKr: "술래잡기! (Tag! You're it!)",
        nameEn: "Tag! You're it!",
        map: "Brownstone High School (브라운스톤 고등학교)",
        quote: "This ghost will chase you immediately, better get running! (이 유령은 즉시 당신을 쫓아올 겁니다, 어서 뛰세요!)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "<strong>시작 0%</strong> / 안정제 회복량 0%",
        speed: "<strong>플레이어 150% (초고속 질주)</strong> / 유령 100%",
        hiding: "보통",
        breaker: "꺼짐",
        weather: "무작위",
        doors: "시작 시 열린 문 많음 / 헌팅 유예 시간 1초",
        cursed: "없음 (None)",
        missingItems: "🚫 없음 (모든 장비 풀세트 지급)",
        availableItems: "📦 모든 조사 및 방어 장비 풀세트",
        strategy: "진입 즉시 정신력 0%로 사냥이 시작되지만 <strong>플레이어 속도가 150%로 엄청나게 빠릅니다.</strong> 고등학교의 긴 복도를 전력 질주하며 유령을 가볍게 따돌릴 수 있으므로, 십자가와 향초를 챙겨 복도 교실들을 수색해 증거를 수집하세요."
    }
];
